project_name: kit
builds:
  - binary: kit
    main: ./cmd/kit/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    goarm:
      - "6"
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.goversion={{.Env.GOVERSION}}
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
brews:
  - name: kit
    tap:
      owner: make-os
      name: homebrew-kit
    commit_author:
      name: MakeOS Team
      email: contact@makeos.org
    folder: Formula
    homepage: "https://makeos.org/"
    description: "A client for the MakeOS decentralized collaboration network"
    dependencies:
      - name: git
    test: |
      system "#{bin}/kit --version"



checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
      - "^dist:"
      - "^scripts:"
      - "^play:"
      - "^mocks:"
