// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	config "github.com/makeos/mosdef/config"
	crypto "github.com/makeos/mosdef/crypto"
	tree "github.com/makeos/mosdef/storage/tree"
	types "github.com/makeos/mosdef/types"
	util "github.com/makeos/mosdef/util"
	logger "github.com/makeos/mosdef/util/logger"
	config0 "gopkg.in/src-d/go-git.v4/config"
	plumbing "gopkg.in/src-d/go-git.v4/plumbing"
	object "gopkg.in/src-d/go-git.v4/plumbing/object"
	storer "gopkg.in/src-d/go-git.v4/plumbing/storer"
	storage "gopkg.in/src-d/go-git.v4/storage"
	reflect "reflect"
	time "time"
)

// MockBareRepo is a mock of BareRepo interface
type MockBareRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBareRepoMockRecorder
}

// MockBareRepoMockRecorder is the mock recorder for MockBareRepo
type MockBareRepoMockRecorder struct {
	mock *MockBareRepo
}

// NewMockBareRepo creates a new mock instance
func NewMockBareRepo(ctrl *gomock.Controller) *MockBareRepo {
	mock := &MockBareRepo{ctrl: ctrl}
	mock.recorder = &MockBareRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBareRepo) EXPECT() *MockBareRepoMockRecorder {
	return m.recorder
}

// GetName mocks base method
func (m *MockBareRepo) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName
func (mr *MockBareRepoMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockBareRepo)(nil).GetName))
}

// References mocks base method
func (m *MockBareRepo) References() (storer.ReferenceIter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "References")
	ret0, _ := ret[0].(storer.ReferenceIter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// References indicates an expected call of References
func (mr *MockBareRepoMockRecorder) References() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "References", reflect.TypeOf((*MockBareRepo)(nil).References))
}

// RefDelete mocks base method
func (m *MockBareRepo) RefDelete(refname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefDelete", refname)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefDelete indicates an expected call of RefDelete
func (mr *MockBareRepoMockRecorder) RefDelete(refname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefDelete", reflect.TypeOf((*MockBareRepo)(nil).RefDelete), refname)
}

// RefUpdate mocks base method
func (m *MockBareRepo) RefUpdate(refname, commitHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefUpdate", refname, commitHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefUpdate indicates an expected call of RefUpdate
func (mr *MockBareRepoMockRecorder) RefUpdate(refname, commitHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefUpdate", reflect.TypeOf((*MockBareRepo)(nil).RefUpdate), refname, commitHash)
}

// RefGet mocks base method
func (m *MockBareRepo) RefGet(refname string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefGet", refname)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefGet indicates an expected call of RefGet
func (mr *MockBareRepoMockRecorder) RefGet(refname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefGet", reflect.TypeOf((*MockBareRepo)(nil).RefGet), refname)
}

// TagDelete mocks base method
func (m *MockBareRepo) TagDelete(tagname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagDelete", tagname)
	ret0, _ := ret[0].(error)
	return ret0
}

// TagDelete indicates an expected call of TagDelete
func (mr *MockBareRepoMockRecorder) TagDelete(tagname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagDelete", reflect.TypeOf((*MockBareRepo)(nil).TagDelete), tagname)
}

// ListTreeObjects mocks base method
func (m *MockBareRepo) ListTreeObjects(treename string, recursive bool, env ...string) (map[string]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{treename, recursive}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTreeObjects", varargs...)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTreeObjects indicates an expected call of ListTreeObjects
func (mr *MockBareRepoMockRecorder) ListTreeObjects(treename, recursive interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{treename, recursive}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTreeObjects", reflect.TypeOf((*MockBareRepo)(nil).ListTreeObjects), varargs...)
}

// DeleteObject mocks base method
func (m *MockBareRepo) DeleteObject(hash plumbing.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject
func (mr *MockBareRepoMockRecorder) DeleteObject(hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockBareRepo)(nil).DeleteObject), hash)
}

// Reference mocks base method
func (m *MockBareRepo) Reference(name plumbing.ReferenceName, resolved bool) (*plumbing.Reference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reference", name, resolved)
	ret0, _ := ret[0].(*plumbing.Reference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reference indicates an expected call of Reference
func (mr *MockBareRepoMockRecorder) Reference(name, resolved interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reference", reflect.TypeOf((*MockBareRepo)(nil).Reference), name, resolved)
}

// Object mocks base method
func (m *MockBareRepo) Object(t plumbing.ObjectType, h plumbing.Hash) (object.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Object", t, h)
	ret0, _ := ret[0].(object.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Object indicates an expected call of Object
func (mr *MockBareRepoMockRecorder) Object(t, h interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Object", reflect.TypeOf((*MockBareRepo)(nil).Object), t, h)
}

// Objects mocks base method
func (m *MockBareRepo) Objects() (*object.ObjectIter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Objects")
	ret0, _ := ret[0].(*object.ObjectIter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Objects indicates an expected call of Objects
func (mr *MockBareRepoMockRecorder) Objects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Objects", reflect.TypeOf((*MockBareRepo)(nil).Objects))
}

// CommitObjects mocks base method
func (m *MockBareRepo) CommitObjects() (object.CommitIter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitObjects")
	ret0, _ := ret[0].(object.CommitIter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitObjects indicates an expected call of CommitObjects
func (mr *MockBareRepoMockRecorder) CommitObjects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitObjects", reflect.TypeOf((*MockBareRepo)(nil).CommitObjects))
}

// CommitObject mocks base method
func (m *MockBareRepo) CommitObject(h plumbing.Hash) (*object.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitObject", h)
	ret0, _ := ret[0].(*object.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitObject indicates an expected call of CommitObject
func (mr *MockBareRepoMockRecorder) CommitObject(h interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitObject", reflect.TypeOf((*MockBareRepo)(nil).CommitObject), h)
}

// MergeBranch mocks base method
func (m *MockBareRepo) MergeBranch(base, target, targetRepoDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeBranch", base, target, targetRepoDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeBranch indicates an expected call of MergeBranch
func (mr *MockBareRepoMockRecorder) MergeBranch(base, target, targetRepoDir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeBranch", reflect.TypeOf((*MockBareRepo)(nil).MergeBranch), base, target, targetRepoDir)
}

// TryMergeBranch mocks base method
func (m *MockBareRepo) TryMergeBranch(base, target, targetRepoDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryMergeBranch", base, target, targetRepoDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// TryMergeBranch indicates an expected call of TryMergeBranch
func (mr *MockBareRepoMockRecorder) TryMergeBranch(base, target, targetRepoDir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryMergeBranch", reflect.TypeOf((*MockBareRepo)(nil).TryMergeBranch), base, target, targetRepoDir)
}

// BlobObject mocks base method
func (m *MockBareRepo) BlobObject(h plumbing.Hash) (*object.Blob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlobObject", h)
	ret0, _ := ret[0].(*object.Blob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlobObject indicates an expected call of BlobObject
func (mr *MockBareRepoMockRecorder) BlobObject(h interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlobObject", reflect.TypeOf((*MockBareRepo)(nil).BlobObject), h)
}

// TagObject mocks base method
func (m *MockBareRepo) TagObject(h plumbing.Hash) (*object.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagObject", h)
	ret0, _ := ret[0].(*object.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagObject indicates an expected call of TagObject
func (mr *MockBareRepoMockRecorder) TagObject(h interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagObject", reflect.TypeOf((*MockBareRepo)(nil).TagObject), h)
}

// Tag mocks base method
func (m *MockBareRepo) Tag(name string) (*plumbing.Reference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tag", name)
	ret0, _ := ret[0].(*plumbing.Reference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tag indicates an expected call of Tag
func (mr *MockBareRepoMockRecorder) Tag(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tag", reflect.TypeOf((*MockBareRepo)(nil).Tag), name)
}

// Config mocks base method
func (m *MockBareRepo) Config() (*config0.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*config0.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Config indicates an expected call of Config
func (mr *MockBareRepoMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockBareRepo)(nil).Config))
}

// GetConfig mocks base method
func (m *MockBareRepo) GetConfig(path string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", path)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfig indicates an expected call of GetConfig
func (mr *MockBareRepoMockRecorder) GetConfig(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockBareRepo)(nil).GetConfig), path)
}

// GetRecentCommit mocks base method
func (m *MockBareRepo) GetRecentCommit() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentCommit")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentCommit indicates an expected call of GetRecentCommit
func (mr *MockBareRepoMockRecorder) GetRecentCommit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentCommit", reflect.TypeOf((*MockBareRepo)(nil).GetRecentCommit))
}

// MakeSignableCommit mocks base method
func (m *MockBareRepo) MakeSignableCommit(msg, signingKey string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{msg, signingKey}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MakeSignableCommit", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// MakeSignableCommit indicates an expected call of MakeSignableCommit
func (mr *MockBareRepoMockRecorder) MakeSignableCommit(msg, signingKey interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{msg, signingKey}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeSignableCommit", reflect.TypeOf((*MockBareRepo)(nil).MakeSignableCommit), varargs...)
}

// CreateTagWithMsg mocks base method
func (m *MockBareRepo) CreateTagWithMsg(args []string, msg, signingKey string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{args, msg, signingKey}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTagWithMsg", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTagWithMsg indicates an expected call of CreateTagWithMsg
func (mr *MockBareRepoMockRecorder) CreateTagWithMsg(args, msg, signingKey interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{args, msg, signingKey}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTagWithMsg", reflect.TypeOf((*MockBareRepo)(nil).CreateTagWithMsg), varargs...)
}

// RemoveEntryFromNote mocks base method
func (m *MockBareRepo) RemoveEntryFromNote(notename, objectHash string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{notename, objectHash}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveEntryFromNote", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveEntryFromNote indicates an expected call of RemoveEntryFromNote
func (mr *MockBareRepoMockRecorder) RemoveEntryFromNote(notename, objectHash interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{notename, objectHash}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEntryFromNote", reflect.TypeOf((*MockBareRepo)(nil).RemoveEntryFromNote), varargs...)
}

// CreateBlob mocks base method
func (m *MockBareRepo) CreateBlob(content string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlob", content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlob indicates an expected call of CreateBlob
func (mr *MockBareRepoMockRecorder) CreateBlob(content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlob", reflect.TypeOf((*MockBareRepo)(nil).CreateBlob), content)
}

// UpdateRecentCommitMsg mocks base method
func (m *MockBareRepo) UpdateRecentCommitMsg(msg, signingKey string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{msg, signingKey}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateRecentCommitMsg", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRecentCommitMsg indicates an expected call of UpdateRecentCommitMsg
func (mr *MockBareRepoMockRecorder) UpdateRecentCommitMsg(msg, signingKey interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{msg, signingKey}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecentCommitMsg", reflect.TypeOf((*MockBareRepo)(nil).UpdateRecentCommitMsg), varargs...)
}

// UpdateTree mocks base method
func (m *MockBareRepo) UpdateTree(ref string, updater func(*tree.SafeTree) error) ([]byte, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTree", ref, updater)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateTree indicates an expected call of UpdateTree
func (mr *MockBareRepoMockRecorder) UpdateTree(ref, updater interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTree", reflect.TypeOf((*MockBareRepo)(nil).UpdateTree), ref, updater)
}

// TreeRoot mocks base method
func (m *MockBareRepo) TreeRoot(ref string) (util.Bytes32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TreeRoot", ref)
	ret0, _ := ret[0].(util.Bytes32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TreeRoot indicates an expected call of TreeRoot
func (mr *MockBareRepoMockRecorder) TreeRoot(ref interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TreeRoot", reflect.TypeOf((*MockBareRepo)(nil).TreeRoot), ref)
}

// AddEntryToNote mocks base method
func (m *MockBareRepo) AddEntryToNote(notename, objectHash, note string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{notename, objectHash, note}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddEntryToNote", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEntryToNote indicates an expected call of AddEntryToNote
func (mr *MockBareRepoMockRecorder) AddEntryToNote(notename, objectHash, note interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{notename, objectHash, note}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEntryToNote", reflect.TypeOf((*MockBareRepo)(nil).AddEntryToNote), varargs...)
}

// ListTreeObjectsSlice mocks base method
func (m *MockBareRepo) ListTreeObjectsSlice(treename string, recursive, showTrees bool, env ...string) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{treename, recursive, showTrees}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTreeObjectsSlice", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTreeObjectsSlice indicates an expected call of ListTreeObjectsSlice
func (mr *MockBareRepoMockRecorder) ListTreeObjectsSlice(treename, recursive, showTrees interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{treename, recursive, showTrees}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTreeObjectsSlice", reflect.TypeOf((*MockBareRepo)(nil).ListTreeObjectsSlice), varargs...)
}

// SetPath mocks base method
func (m *MockBareRepo) SetPath(path string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPath", path)
}

// SetPath indicates an expected call of SetPath
func (mr *MockBareRepoMockRecorder) SetPath(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPath", reflect.TypeOf((*MockBareRepo)(nil).SetPath), path)
}

// Path mocks base method
func (m *MockBareRepo) Path() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path")
	ret0, _ := ret[0].(string)
	return ret0
}

// Path indicates an expected call of Path
func (mr *MockBareRepoMockRecorder) Path() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockBareRepo)(nil).Path))
}

// State mocks base method
func (m *MockBareRepo) State() *types.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "State")
	ret0, _ := ret[0].(*types.Repository)
	return ret0
}

// State indicates an expected call of State
func (mr *MockBareRepoMockRecorder) State() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "State", reflect.TypeOf((*MockBareRepo)(nil).State))
}

// ObjectExist mocks base method
func (m *MockBareRepo) ObjectExist(objHash string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ObjectExist", objHash)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ObjectExist indicates an expected call of ObjectExist
func (mr *MockBareRepoMockRecorder) ObjectExist(objHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObjectExist", reflect.TypeOf((*MockBareRepo)(nil).ObjectExist), objHash)
}

// GetObjectSize mocks base method
func (m *MockBareRepo) GetObjectSize(objHash string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectSize", objHash)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectSize indicates an expected call of GetObjectSize
func (mr *MockBareRepoMockRecorder) GetObjectSize(objHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectSize", reflect.TypeOf((*MockBareRepo)(nil).GetObjectSize), objHash)
}

// GetObjectDiskSize mocks base method
func (m *MockBareRepo) GetObjectDiskSize(objHash string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectDiskSize", objHash)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectDiskSize indicates an expected call of GetObjectDiskSize
func (mr *MockBareRepoMockRecorder) GetObjectDiskSize(objHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectDiskSize", reflect.TypeOf((*MockBareRepo)(nil).GetObjectDiskSize), objHash)
}

// GetEncodedObject mocks base method
func (m *MockBareRepo) GetEncodedObject(objHash string) (plumbing.EncodedObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncodedObject", objHash)
	ret0, _ := ret[0].(plumbing.EncodedObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncodedObject indicates an expected call of GetEncodedObject
func (mr *MockBareRepoMockRecorder) GetEncodedObject(objHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncodedObject", reflect.TypeOf((*MockBareRepo)(nil).GetEncodedObject), objHash)
}

// WriteObjectToFile mocks base method
func (m *MockBareRepo) WriteObjectToFile(objectHash string, content []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteObjectToFile", objectHash, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteObjectToFile indicates an expected call of WriteObjectToFile
func (mr *MockBareRepoMockRecorder) WriteObjectToFile(objectHash, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteObjectToFile", reflect.TypeOf((*MockBareRepo)(nil).WriteObjectToFile), objectHash, content)
}

// GetObject mocks base method
func (m *MockBareRepo) GetObject(objHash string) (object.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", objHash)
	ret0, _ := ret[0].(object.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject
func (mr *MockBareRepoMockRecorder) GetObject(objHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockBareRepo)(nil).GetObject), objHash)
}

// GetCompressedObject mocks base method
func (m *MockBareRepo) GetCompressedObject(hash string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompressedObject", hash)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompressedObject indicates an expected call of GetCompressedObject
func (mr *MockBareRepoMockRecorder) GetCompressedObject(hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompressedObject", reflect.TypeOf((*MockBareRepo)(nil).GetCompressedObject), hash)
}

// GetStorer mocks base method
func (m *MockBareRepo) GetStorer() storage.Storer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorer")
	ret0, _ := ret[0].(storage.Storer)
	return ret0
}

// GetStorer indicates an expected call of GetStorer
func (mr *MockBareRepoMockRecorder) GetStorer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorer", reflect.TypeOf((*MockBareRepo)(nil).GetStorer))
}

// Prune mocks base method
func (m *MockBareRepo) Prune(olderThan time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prune", olderThan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Prune indicates an expected call of Prune
func (mr *MockBareRepoMockRecorder) Prune(olderThan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prune", reflect.TypeOf((*MockBareRepo)(nil).Prune), olderThan)
}

// MockPoolGetter is a mock of PoolGetter interface
type MockPoolGetter struct {
	ctrl     *gomock.Controller
	recorder *MockPoolGetterMockRecorder
}

// MockPoolGetterMockRecorder is the mock recorder for MockPoolGetter
type MockPoolGetterMockRecorder struct {
	mock *MockPoolGetter
}

// NewMockPoolGetter creates a new mock instance
func NewMockPoolGetter(ctrl *gomock.Controller) *MockPoolGetter {
	mock := &MockPoolGetter{ctrl: ctrl}
	mock.recorder = &MockPoolGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPoolGetter) EXPECT() *MockPoolGetterMockRecorder {
	return m.recorder
}

// GetPushPool mocks base method
func (m *MockPoolGetter) GetPushPool() types.PushPool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushPool")
	ret0, _ := ret[0].(types.PushPool)
	return ret0
}

// GetPushPool indicates an expected call of GetPushPool
func (mr *MockPoolGetterMockRecorder) GetPushPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushPool", reflect.TypeOf((*MockPoolGetter)(nil).GetPushPool))
}

// GetMempool mocks base method
func (m *MockPoolGetter) GetMempool() types.Mempool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMempool")
	ret0, _ := ret[0].(types.Mempool)
	return ret0
}

// GetMempool indicates an expected call of GetMempool
func (mr *MockPoolGetterMockRecorder) GetMempool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMempool", reflect.TypeOf((*MockPoolGetter)(nil).GetMempool))
}

// MockRepoManager is a mock of RepoManager interface
type MockRepoManager struct {
	ctrl     *gomock.Controller
	recorder *MockRepoManagerMockRecorder
}

// MockRepoManagerMockRecorder is the mock recorder for MockRepoManager
type MockRepoManagerMockRecorder struct {
	mock *MockRepoManager
}

// NewMockRepoManager creates a new mock instance
func NewMockRepoManager(ctrl *gomock.Controller) *MockRepoManager {
	mock := &MockRepoManager{ctrl: ctrl}
	mock.recorder = &MockRepoManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepoManager) EXPECT() *MockRepoManagerMockRecorder {
	return m.recorder
}

// GetPushPool mocks base method
func (m *MockRepoManager) GetPushPool() types.PushPool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushPool")
	ret0, _ := ret[0].(types.PushPool)
	return ret0
}

// GetPushPool indicates an expected call of GetPushPool
func (mr *MockRepoManagerMockRecorder) GetPushPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushPool", reflect.TypeOf((*MockRepoManager)(nil).GetPushPool))
}

// GetMempool mocks base method
func (m *MockRepoManager) GetMempool() types.Mempool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMempool")
	ret0, _ := ret[0].(types.Mempool)
	return ret0
}

// GetMempool indicates an expected call of GetMempool
func (mr *MockRepoManagerMockRecorder) GetMempool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMempool", reflect.TypeOf((*MockRepoManager)(nil).GetMempool))
}

// GetRepo mocks base method
func (m *MockRepoManager) GetRepo(name string) (types.BareRepo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepo", name)
	ret0, _ := ret[0].(types.BareRepo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepo indicates an expected call of GetRepo
func (mr *MockRepoManagerMockRecorder) GetRepo(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepo", reflect.TypeOf((*MockRepoManager)(nil).GetRepo), name)
}

// UpdateRepoWithTxPush mocks base method
func (m *MockRepoManager) UpdateRepoWithTxPush(tx *types.TxPush) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRepoWithTxPush", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRepoWithTxPush indicates an expected call of UpdateRepoWithTxPush
func (mr *MockRepoManagerMockRecorder) UpdateRepoWithTxPush(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRepoWithTxPush", reflect.TypeOf((*MockRepoManager)(nil).UpdateRepoWithTxPush), tx)
}

// Log mocks base method
func (m *MockRepoManager) Log() logger.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log")
	ret0, _ := ret[0].(logger.Logger)
	return ret0
}

// Log indicates an expected call of Log
func (mr *MockRepoManagerMockRecorder) Log() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockRepoManager)(nil).Log))
}

// Cfg mocks base method
func (m *MockRepoManager) Cfg() *config.AppConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cfg")
	ret0, _ := ret[0].(*config.AppConfig)
	return ret0
}

// Cfg indicates an expected call of Cfg
func (mr *MockRepoManagerMockRecorder) Cfg() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cfg", reflect.TypeOf((*MockRepoManager)(nil).Cfg))
}

// GetRepoState mocks base method
func (m *MockRepoManager) GetRepoState(target types.BareRepo, options ...types.KVOption) (types.BareRepoState, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{target}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRepoState", varargs...)
	ret0, _ := ret[0].(types.BareRepoState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepoState indicates an expected call of GetRepoState
func (mr *MockRepoManagerMockRecorder) GetRepoState(target interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{target}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepoState", reflect.TypeOf((*MockRepoManager)(nil).GetRepoState), varargs...)
}

// GetPGPPubKeyGetter mocks base method
func (m *MockRepoManager) GetPGPPubKeyGetter() types.PGPPubKeyGetter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPGPPubKeyGetter")
	ret0, _ := ret[0].(types.PGPPubKeyGetter)
	return ret0
}

// GetPGPPubKeyGetter indicates an expected call of GetPGPPubKeyGetter
func (mr *MockRepoManagerMockRecorder) GetPGPPubKeyGetter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPGPPubKeyGetter", reflect.TypeOf((*MockRepoManager)(nil).GetPGPPubKeyGetter))
}

// GetLogic mocks base method
func (m *MockRepoManager) GetLogic() types.Logic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogic")
	ret0, _ := ret[0].(types.Logic)
	return ret0
}

// GetLogic indicates an expected call of GetLogic
func (mr *MockRepoManagerMockRecorder) GetLogic() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogic", reflect.TypeOf((*MockRepoManager)(nil).GetLogic))
}

// GetPrivateValidatorKey mocks base method
func (m *MockRepoManager) GetPrivateValidatorKey() *crypto.Key {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateValidatorKey")
	ret0, _ := ret[0].(*crypto.Key)
	return ret0
}

// GetPrivateValidatorKey indicates an expected call of GetPrivateValidatorKey
func (mr *MockRepoManagerMockRecorder) GetPrivateValidatorKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateValidatorKey", reflect.TypeOf((*MockRepoManager)(nil).GetPrivateValidatorKey))
}

// Start mocks base method
func (m *MockRepoManager) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start
func (mr *MockRepoManagerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRepoManager)(nil).Start))
}

// Wait mocks base method
func (m *MockRepoManager) Wait() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Wait")
}

// Wait indicates an expected call of Wait
func (mr *MockRepoManagerMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockRepoManager)(nil).Wait))
}

// CreateRepository mocks base method
func (m *MockRepoManager) CreateRepository(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRepository", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRepository indicates an expected call of CreateRepository
func (mr *MockRepoManagerMockRecorder) CreateRepository(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRepository", reflect.TypeOf((*MockRepoManager)(nil).CreateRepository), name)
}

// BroadcastMsg mocks base method
func (m *MockRepoManager) BroadcastMsg(ch byte, msg []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastMsg", ch, msg)
}

// BroadcastMsg indicates an expected call of BroadcastMsg
func (mr *MockRepoManagerMockRecorder) BroadcastMsg(ch, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastMsg", reflect.TypeOf((*MockRepoManager)(nil).BroadcastMsg), ch, msg)
}

// BroadcastPushObjects mocks base method
func (m *MockRepoManager) BroadcastPushObjects(pushNote types.RepoPushNote) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastPushObjects", pushNote)
	ret0, _ := ret[0].(error)
	return ret0
}

// BroadcastPushObjects indicates an expected call of BroadcastPushObjects
func (mr *MockRepoManagerMockRecorder) BroadcastPushObjects(pushNote interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastPushObjects", reflect.TypeOf((*MockRepoManager)(nil).BroadcastPushObjects), pushNote)
}

// SetPGPPubKeyGetter mocks base method
func (m *MockRepoManager) SetPGPPubKeyGetter(pkGetter types.PGPPubKeyGetter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPGPPubKeyGetter", pkGetter)
}

// SetPGPPubKeyGetter indicates an expected call of SetPGPPubKeyGetter
func (mr *MockRepoManagerMockRecorder) SetPGPPubKeyGetter(pkGetter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPGPPubKeyGetter", reflect.TypeOf((*MockRepoManager)(nil).SetPGPPubKeyGetter), pkGetter)
}

// SetModulesAgg mocks base method
func (m *MockRepoManager) SetModulesAgg(agg types.ModulesAggregator) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetModulesAgg", agg)
}

// SetModulesAgg indicates an expected call of SetModulesAgg
func (mr *MockRepoManagerMockRecorder) SetModulesAgg(agg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetModulesAgg", reflect.TypeOf((*MockRepoManager)(nil).SetModulesAgg), agg)
}

// GetPruner mocks base method
func (m *MockRepoManager) GetPruner() types.Pruner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPruner")
	ret0, _ := ret[0].(types.Pruner)
	return ret0
}

// GetPruner indicates an expected call of GetPruner
func (mr *MockRepoManagerMockRecorder) GetPruner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPruner", reflect.TypeOf((*MockRepoManager)(nil).GetPruner))
}

// GetDHT mocks base method
func (m *MockRepoManager) GetDHT() types.DHT {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDHT")
	ret0, _ := ret[0].(types.DHT)
	return ret0
}

// GetDHT indicates an expected call of GetDHT
func (mr *MockRepoManagerMockRecorder) GetDHT() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDHT", reflect.TypeOf((*MockRepoManager)(nil).GetDHT))
}

// ExecTxPush mocks base method
func (m *MockRepoManager) ExecTxPush(tx *types.TxPush) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecTxPush", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecTxPush indicates an expected call of ExecTxPush
func (mr *MockRepoManagerMockRecorder) ExecTxPush(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecTxPush", reflect.TypeOf((*MockRepoManager)(nil).ExecTxPush), tx)
}

// Shutdown mocks base method
func (m *MockRepoManager) Shutdown(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown", ctx)
}

// Shutdown indicates an expected call of Shutdown
func (mr *MockRepoManagerMockRecorder) Shutdown(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockRepoManager)(nil).Shutdown), ctx)
}

// Stop mocks base method
func (m *MockRepoManager) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop
func (mr *MockRepoManagerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockRepoManager)(nil).Stop))
}

// MockRepoGetter is a mock of RepoGetter interface
type MockRepoGetter struct {
	ctrl     *gomock.Controller
	recorder *MockRepoGetterMockRecorder
}

// MockRepoGetterMockRecorder is the mock recorder for MockRepoGetter
type MockRepoGetterMockRecorder struct {
	mock *MockRepoGetter
}

// NewMockRepoGetter creates a new mock instance
func NewMockRepoGetter(ctrl *gomock.Controller) *MockRepoGetter {
	mock := &MockRepoGetter{ctrl: ctrl}
	mock.recorder = &MockRepoGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepoGetter) EXPECT() *MockRepoGetterMockRecorder {
	return m.recorder
}

// GetRepo mocks base method
func (m *MockRepoGetter) GetRepo(name string) (types.BareRepo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepo", name)
	ret0, _ := ret[0].(types.BareRepo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepo indicates an expected call of GetRepo
func (mr *MockRepoGetterMockRecorder) GetRepo(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepo", reflect.TypeOf((*MockRepoGetter)(nil).GetRepo), name)
}

// MockTxPushMerger is a mock of TxPushMerger interface
type MockTxPushMerger struct {
	ctrl     *gomock.Controller
	recorder *MockTxPushMergerMockRecorder
}

// MockTxPushMergerMockRecorder is the mock recorder for MockTxPushMerger
type MockTxPushMergerMockRecorder struct {
	mock *MockTxPushMerger
}

// NewMockTxPushMerger creates a new mock instance
func NewMockTxPushMerger(ctrl *gomock.Controller) *MockTxPushMerger {
	mock := &MockTxPushMerger{ctrl: ctrl}
	mock.recorder = &MockTxPushMergerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTxPushMerger) EXPECT() *MockTxPushMergerMockRecorder {
	return m.recorder
}

// UpdateRepoWithTxPush mocks base method
func (m *MockTxPushMerger) UpdateRepoWithTxPush(tx *types.TxPush) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRepoWithTxPush", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRepoWithTxPush indicates an expected call of UpdateRepoWithTxPush
func (mr *MockTxPushMergerMockRecorder) UpdateRepoWithTxPush(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRepoWithTxPush", reflect.TypeOf((*MockTxPushMerger)(nil).UpdateRepoWithTxPush), tx)
}

// MockUnfinalizedObjectCache is a mock of UnfinalizedObjectCache interface
type MockUnfinalizedObjectCache struct {
	ctrl     *gomock.Controller
	recorder *MockUnfinalizedObjectCacheMockRecorder
}

// MockUnfinalizedObjectCacheMockRecorder is the mock recorder for MockUnfinalizedObjectCache
type MockUnfinalizedObjectCacheMockRecorder struct {
	mock *MockUnfinalizedObjectCache
}

// NewMockUnfinalizedObjectCache creates a new mock instance
func NewMockUnfinalizedObjectCache(ctrl *gomock.Controller) *MockUnfinalizedObjectCache {
	mock := &MockUnfinalizedObjectCache{ctrl: ctrl}
	mock.recorder = &MockUnfinalizedObjectCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUnfinalizedObjectCache) EXPECT() *MockUnfinalizedObjectCacheMockRecorder {
	return m.recorder
}

// AddUnfinalizedObject mocks base method
func (m *MockUnfinalizedObjectCache) AddUnfinalizedObject(repo, objHash string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddUnfinalizedObject", repo, objHash)
}

// AddUnfinalizedObject indicates an expected call of AddUnfinalizedObject
func (mr *MockUnfinalizedObjectCacheMockRecorder) AddUnfinalizedObject(repo, objHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUnfinalizedObject", reflect.TypeOf((*MockUnfinalizedObjectCache)(nil).AddUnfinalizedObject), repo, objHash)
}

// RemoveUnfinalizedObject mocks base method
func (m *MockUnfinalizedObjectCache) RemoveUnfinalizedObject(repo, objHash string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveUnfinalizedObject", repo, objHash)
}

// RemoveUnfinalizedObject indicates an expected call of RemoveUnfinalizedObject
func (mr *MockUnfinalizedObjectCacheMockRecorder) RemoveUnfinalizedObject(repo, objHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUnfinalizedObject", reflect.TypeOf((*MockUnfinalizedObjectCache)(nil).RemoveUnfinalizedObject), repo, objHash)
}

// IsUnfinalizedObject mocks base method
func (m *MockUnfinalizedObjectCache) IsUnfinalizedObject(repo, objHash string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUnfinalizedObject", repo, objHash)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUnfinalizedObject indicates an expected call of IsUnfinalizedObject
func (mr *MockUnfinalizedObjectCacheMockRecorder) IsUnfinalizedObject(repo, objHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUnfinalizedObject", reflect.TypeOf((*MockUnfinalizedObjectCache)(nil).IsUnfinalizedObject), repo, objHash)
}

// MockPushPool is a mock of PushPool interface
type MockPushPool struct {
	ctrl     *gomock.Controller
	recorder *MockPushPoolMockRecorder
}

// MockPushPoolMockRecorder is the mock recorder for MockPushPool
type MockPushPoolMockRecorder struct {
	mock *MockPushPool
}

// NewMockPushPool creates a new mock instance
func NewMockPushPool(ctrl *gomock.Controller) *MockPushPool {
	mock := &MockPushPool{ctrl: ctrl}
	mock.recorder = &MockPushPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPushPool) EXPECT() *MockPushPoolMockRecorder {
	return m.recorder
}

// Add mocks base method
func (m *MockPushPool) Add(tx types.RepoPushNote, noValidation ...bool) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{tx}
	for _, a := range noValidation {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Add", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add
func (mr *MockPushPoolMockRecorder) Add(tx interface{}, noValidation ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{tx}, noValidation...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockPushPool)(nil).Add), varargs...)
}

// Full mocks base method
func (m *MockPushPool) Full() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Full")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Full indicates an expected call of Full
func (mr *MockPushPoolMockRecorder) Full() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Full", reflect.TypeOf((*MockPushPool)(nil).Full))
}

// RepoHasPushNote mocks base method
func (m *MockPushPool) RepoHasPushNote(repo string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoHasPushNote", repo)
	ret0, _ := ret[0].(bool)
	return ret0
}

// RepoHasPushNote indicates an expected call of RepoHasPushNote
func (mr *MockPushPoolMockRecorder) RepoHasPushNote(repo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoHasPushNote", reflect.TypeOf((*MockPushPool)(nil).RepoHasPushNote), repo)
}

// Get mocks base method
func (m *MockPushPool) Get(noteID string) *types.PushNote {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", noteID)
	ret0, _ := ret[0].(*types.PushNote)
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockPushPoolMockRecorder) Get(noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPushPool)(nil).Get), noteID)
}

// Len mocks base method
func (m *MockPushPool) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len
func (mr *MockPushPoolMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockPushPool)(nil).Len))
}

// Remove mocks base method
func (m *MockPushPool) Remove(pushNote *types.PushNote) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", pushNote)
}

// Remove indicates an expected call of Remove
func (mr *MockPushPoolMockRecorder) Remove(pushNote interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockPushPool)(nil).Remove), pushNote)
}

// MockRepoPushNote is a mock of RepoPushNote interface
type MockRepoPushNote struct {
	ctrl     *gomock.Controller
	recorder *MockRepoPushNoteMockRecorder
}

// MockRepoPushNoteMockRecorder is the mock recorder for MockRepoPushNote
type MockRepoPushNoteMockRecorder struct {
	mock *MockRepoPushNote
}

// NewMockRepoPushNote creates a new mock instance
func NewMockRepoPushNote(ctrl *gomock.Controller) *MockRepoPushNote {
	mock := &MockRepoPushNote{ctrl: ctrl}
	mock.recorder = &MockRepoPushNoteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepoPushNote) EXPECT() *MockRepoPushNoteMockRecorder {
	return m.recorder
}

// GetRepoName mocks base method
func (m *MockRepoPushNote) GetRepoName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepoName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRepoName indicates an expected call of GetRepoName
func (mr *MockRepoPushNoteMockRecorder) GetRepoName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepoName", reflect.TypeOf((*MockRepoPushNote)(nil).GetRepoName))
}

// Bytes mocks base method
func (m *MockRepoPushNote) Bytes() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bytes")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Bytes indicates an expected call of Bytes
func (mr *MockRepoPushNoteMockRecorder) Bytes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bytes", reflect.TypeOf((*MockRepoPushNote)(nil).Bytes))
}

// GetEcoSize mocks base method
func (m *MockRepoPushNote) GetEcoSize() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEcoSize")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetEcoSize indicates an expected call of GetEcoSize
func (mr *MockRepoPushNoteMockRecorder) GetEcoSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEcoSize", reflect.TypeOf((*MockRepoPushNote)(nil).GetEcoSize))
}

// Len mocks base method
func (m *MockRepoPushNote) Len() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Len indicates an expected call of Len
func (mr *MockRepoPushNoteMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockRepoPushNote)(nil).Len))
}

// ID mocks base method
func (m *MockRepoPushNote) ID() util.Bytes32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(util.Bytes32)
	return ret0
}

// ID indicates an expected call of ID
func (mr *MockRepoPushNoteMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockRepoPushNote)(nil).ID))
}

// TxSize mocks base method
func (m *MockRepoPushNote) TxSize() uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxSize")
	ret0, _ := ret[0].(uint)
	return ret0
}

// TxSize indicates an expected call of TxSize
func (mr *MockRepoPushNoteMockRecorder) TxSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxSize", reflect.TypeOf((*MockRepoPushNote)(nil).TxSize))
}

// BillableSize mocks base method
func (m *MockRepoPushNote) BillableSize() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BillableSize")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// BillableSize indicates an expected call of BillableSize
func (mr *MockRepoPushNoteMockRecorder) BillableSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BillableSize", reflect.TypeOf((*MockRepoPushNote)(nil).BillableSize))
}

// GetFee mocks base method
func (m *MockRepoPushNote) GetFee() util.String {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFee")
	ret0, _ := ret[0].(util.String)
	return ret0
}

// GetFee indicates an expected call of GetFee
func (mr *MockRepoPushNoteMockRecorder) GetFee() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFee", reflect.TypeOf((*MockRepoPushNote)(nil).GetFee))
}

// GetPushedReferences mocks base method
func (m *MockRepoPushNote) GetPushedReferences() types.PushedReferences {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushedReferences")
	ret0, _ := ret[0].(types.PushedReferences)
	return ret0
}

// GetPushedReferences indicates an expected call of GetPushedReferences
func (mr *MockRepoPushNoteMockRecorder) GetPushedReferences() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushedReferences", reflect.TypeOf((*MockRepoPushNote)(nil).GetPushedReferences))
}

// GetPusherKeyID mocks base method
func (m *MockRepoPushNote) GetPusherKeyID() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPusherKeyID")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetPusherKeyID indicates an expected call of GetPusherKeyID
func (mr *MockRepoPushNoteMockRecorder) GetPusherKeyID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPusherKeyID", reflect.TypeOf((*MockRepoPushNote)(nil).GetPusherKeyID))
}

// GetPusherKeyIDString mocks base method
func (m *MockRepoPushNote) GetPusherKeyIDString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPusherKeyIDString")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPusherKeyIDString indicates an expected call of GetPusherKeyIDString
func (mr *MockRepoPushNoteMockRecorder) GetPusherKeyIDString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPusherKeyIDString", reflect.TypeOf((*MockRepoPushNote)(nil).GetPusherKeyIDString))
}

// GetTargetRepo mocks base method
func (m *MockRepoPushNote) GetTargetRepo() types.BareRepo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetRepo")
	ret0, _ := ret[0].(types.BareRepo)
	return ret0
}

// GetTargetRepo indicates an expected call of GetTargetRepo
func (mr *MockRepoPushNoteMockRecorder) GetTargetRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetRepo", reflect.TypeOf((*MockRepoPushNote)(nil).GetTargetRepo))
}

// GetSize mocks base method
func (m *MockRepoPushNote) GetSize() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSize")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetSize indicates an expected call of GetSize
func (mr *MockRepoPushNoteMockRecorder) GetSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSize", reflect.TypeOf((*MockRepoPushNote)(nil).GetSize))
}

// GetPushedObjects mocks base method
func (m *MockRepoPushNote) GetPushedObjects(ignoreDelRefs bool) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushedObjects", ignoreDelRefs)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetPushedObjects indicates an expected call of GetPushedObjects
func (mr *MockRepoPushNoteMockRecorder) GetPushedObjects(ignoreDelRefs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushedObjects", reflect.TypeOf((*MockRepoPushNote)(nil).GetPushedObjects), ignoreDelRefs)
}

// BytesAndID mocks base method
func (m *MockRepoPushNote) BytesAndID() ([]byte, util.Bytes32) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BytesAndID")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(util.Bytes32)
	return ret0, ret1
}

// BytesAndID indicates an expected call of BytesAndID
func (mr *MockRepoPushNoteMockRecorder) BytesAndID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BytesAndID", reflect.TypeOf((*MockRepoPushNote)(nil).BytesAndID))
}

// MockPruner is a mock of Pruner interface
type MockPruner struct {
	ctrl     *gomock.Controller
	recorder *MockPrunerMockRecorder
}

// MockPrunerMockRecorder is the mock recorder for MockPruner
type MockPrunerMockRecorder struct {
	mock *MockPruner
}

// NewMockPruner creates a new mock instance
func NewMockPruner(ctrl *gomock.Controller) *MockPruner {
	mock := &MockPruner{ctrl: ctrl}
	mock.recorder = &MockPrunerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPruner) EXPECT() *MockPrunerMockRecorder {
	return m.recorder
}

// Start mocks base method
func (m *MockPruner) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start
func (mr *MockPrunerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockPruner)(nil).Start))
}

// Schedule mocks base method
func (m *MockPruner) Schedule(repoName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Schedule", repoName)
}

// Schedule indicates an expected call of Schedule
func (mr *MockPrunerMockRecorder) Schedule(repoName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockPruner)(nil).Schedule), repoName)
}

// Prune mocks base method
func (m *MockPruner) Prune(repoName string, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prune", repoName, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// Prune indicates an expected call of Prune
func (mr *MockPrunerMockRecorder) Prune(repoName, force interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prune", reflect.TypeOf((*MockPruner)(nil).Prune), repoName, force)
}

// Stop mocks base method
func (m *MockPruner) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop
func (mr *MockPrunerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockPruner)(nil).Stop))
}

// MockBareRepoState is a mock of BareRepoState interface
type MockBareRepoState struct {
	ctrl     *gomock.Controller
	recorder *MockBareRepoStateMockRecorder
}

// MockBareRepoStateMockRecorder is the mock recorder for MockBareRepoState
type MockBareRepoStateMockRecorder struct {
	mock *MockBareRepoState
}

// NewMockBareRepoState creates a new mock instance
func NewMockBareRepoState(ctrl *gomock.Controller) *MockBareRepoState {
	mock := &MockBareRepoState{ctrl: ctrl}
	mock.recorder = &MockBareRepoStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBareRepoState) EXPECT() *MockBareRepoStateMockRecorder {
	return m.recorder
}

// GetReferences mocks base method
func (m *MockBareRepoState) GetReferences() types.Items {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferences")
	ret0, _ := ret[0].(types.Items)
	return ret0
}

// GetReferences indicates an expected call of GetReferences
func (mr *MockBareRepoStateMockRecorder) GetReferences() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferences", reflect.TypeOf((*MockBareRepoState)(nil).GetReferences))
}

// IsEmpty mocks base method
func (m *MockBareRepoState) IsEmpty() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmpty")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEmpty indicates an expected call of IsEmpty
func (mr *MockBareRepoStateMockRecorder) IsEmpty() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmpty", reflect.TypeOf((*MockBareRepoState)(nil).IsEmpty))
}

// Hash mocks base method
func (m *MockBareRepoState) Hash() util.Bytes32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash")
	ret0, _ := ret[0].(util.Bytes32)
	return ret0
}

// Hash indicates an expected call of Hash
func (mr *MockBareRepoStateMockRecorder) Hash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockBareRepoState)(nil).Hash))
}

// GetChanges mocks base method
func (m *MockBareRepoState) GetChanges(y types.BareRepoState) *types.Changes {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChanges", y)
	ret0, _ := ret[0].(*types.Changes)
	return ret0
}

// GetChanges indicates an expected call of GetChanges
func (mr *MockBareRepoStateMockRecorder) GetChanges(y interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChanges", reflect.TypeOf((*MockBareRepoState)(nil).GetChanges), y)
}

// MockItem is a mock of Item interface
type MockItem struct {
	ctrl     *gomock.Controller
	recorder *MockItemMockRecorder
}

// MockItemMockRecorder is the mock recorder for MockItem
type MockItemMockRecorder struct {
	mock *MockItem
}

// NewMockItem creates a new mock instance
func NewMockItem(ctrl *gomock.Controller) *MockItem {
	mock := &MockItem{ctrl: ctrl}
	mock.recorder = &MockItemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockItem) EXPECT() *MockItemMockRecorder {
	return m.recorder
}

// GetName mocks base method
func (m *MockItem) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName
func (mr *MockItemMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockItem)(nil).GetName))
}

// Equal mocks base method
func (m *MockItem) Equal(o interface{}) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Equal", o)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Equal indicates an expected call of Equal
func (mr *MockItemMockRecorder) Equal(o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Equal", reflect.TypeOf((*MockItem)(nil).Equal), o)
}

// GetData mocks base method
func (m *MockItem) GetData() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetData indicates an expected call of GetData
func (mr *MockItemMockRecorder) GetData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockItem)(nil).GetData))
}

// GetType mocks base method
func (m *MockItem) GetType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetType indicates an expected call of GetType
func (mr *MockItemMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockItem)(nil).GetType))
}

// MockItems is a mock of Items interface
type MockItems struct {
	ctrl     *gomock.Controller
	recorder *MockItemsMockRecorder
}

// MockItemsMockRecorder is the mock recorder for MockItems
type MockItemsMockRecorder struct {
	mock *MockItems
}

// NewMockItems creates a new mock instance
func NewMockItems(ctrl *gomock.Controller) *MockItems {
	mock := &MockItems{ctrl: ctrl}
	mock.recorder = &MockItemsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockItems) EXPECT() *MockItemsMockRecorder {
	return m.recorder
}

// Has mocks base method
func (m *MockItems) Has(name interface{}) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Has indicates an expected call of Has
func (mr *MockItemsMockRecorder) Has(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockItems)(nil).Has), name)
}

// Get mocks base method
func (m *MockItems) Get(name interface{}) types.Item {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(types.Item)
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockItemsMockRecorder) Get(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockItems)(nil).Get), name)
}

// Equal mocks base method
func (m *MockItems) Equal(o interface{}) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Equal", o)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Equal indicates an expected call of Equal
func (mr *MockItemsMockRecorder) Equal(o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Equal", reflect.TypeOf((*MockItems)(nil).Equal), o)
}

// ForEach mocks base method
func (m *MockItems) ForEach(arg0 func(types.Item) bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ForEach", arg0)
}

// ForEach indicates an expected call of ForEach
func (mr *MockItemsMockRecorder) ForEach(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForEach", reflect.TypeOf((*MockItems)(nil).ForEach), arg0)
}

// Len mocks base method
func (m *MockItems) Len() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Len indicates an expected call of Len
func (mr *MockItemsMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockItems)(nil).Len))
}

// Bytes mocks base method
func (m *MockItems) Bytes() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bytes")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Bytes indicates an expected call of Bytes
func (mr *MockItemsMockRecorder) Bytes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bytes", reflect.TypeOf((*MockItems)(nil).Bytes))
}

// Hash mocks base method
func (m *MockItems) Hash() util.Bytes32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash")
	ret0, _ := ret[0].(util.Bytes32)
	return ret0
}

// Hash indicates an expected call of Hash
func (mr *MockItemsMockRecorder) Hash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockItems)(nil).Hash))
}

// MockRepoPushOK is a mock of RepoPushOK interface
type MockRepoPushOK struct {
	ctrl     *gomock.Controller
	recorder *MockRepoPushOKMockRecorder
}

// MockRepoPushOKMockRecorder is the mock recorder for MockRepoPushOK
type MockRepoPushOKMockRecorder struct {
	mock *MockRepoPushOK
}

// NewMockRepoPushOK creates a new mock instance
func NewMockRepoPushOK(ctrl *gomock.Controller) *MockRepoPushOK {
	mock := &MockRepoPushOK{ctrl: ctrl}
	mock.recorder = &MockRepoPushOKMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepoPushOK) EXPECT() *MockRepoPushOKMockRecorder {
	return m.recorder
}

// ID mocks base method
func (m *MockRepoPushOK) ID() util.Bytes32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(util.Bytes32)
	return ret0
}

// ID indicates an expected call of ID
func (mr *MockRepoPushOKMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockRepoPushOK)(nil).ID))
}

// Bytes mocks base method
func (m *MockRepoPushOK) Bytes() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bytes")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Bytes indicates an expected call of Bytes
func (mr *MockRepoPushOKMockRecorder) Bytes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bytes", reflect.TypeOf((*MockRepoPushOK)(nil).Bytes))
}

// BytesAndID mocks base method
func (m *MockRepoPushOK) BytesAndID() ([]byte, util.Bytes32) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BytesAndID")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(util.Bytes32)
	return ret0, ret1
}

// BytesAndID indicates an expected call of BytesAndID
func (mr *MockRepoPushOKMockRecorder) BytesAndID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BytesAndID", reflect.TypeOf((*MockRepoPushOK)(nil).BytesAndID))
}
