// Code generated by MockGen. DO NOT EDIT.
// Source: remote/pushpool/types/pushnote.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	msgpack "github.com/vmihailenco/msgpack"
	"gitlab.com/makeos/mosdef/remote/push/types"
	types2 "gitlab.com/makeos/mosdef/remote/types"
	state "gitlab.com/makeos/mosdef/types/state"
	util "gitlab.com/makeos/mosdef/util"
	config "gopkg.in/src-d/go-git.v4/config"
	plumbing "gopkg.in/src-d/go-git.v4/plumbing"
	object "gopkg.in/src-d/go-git.v4/plumbing/object"
	storer "gopkg.in/src-d/go-git.v4/plumbing/storer"
	storage "gopkg.in/src-d/go-git.v4/storage"
)

// MockPushNotice is a mock of PushNotice interface
type MockPushNotice struct {
	ctrl     *gomock.Controller
	recorder *MockPushNoticeMockRecorder
}

// MockPushNoticeMockRecorder is the mock recorder for MockPushNotice
type MockPushNoticeMockRecorder struct {
	mock *MockPushNotice
}

// NewMockPushNotice creates a new mock instance
func NewMockPushNotice(ctrl *gomock.Controller) *MockPushNotice {
	mock := &MockPushNotice{ctrl: ctrl}
	mock.recorder = &MockPushNoticeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPushNotice) EXPECT() *MockPushNoticeMockRecorder {
	return m.recorder
}

// GetTargetRepo mocks base method
func (m *MockPushNotice) GetTargetRepo() types2.LocalRepo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetRepo")
	ret0, _ := ret[0].(types2.LocalRepo)
	return ret0
}

// GetTargetRepo indicates an expected call of GetTargetRepo
func (mr *MockPushNoticeMockRecorder) GetTargetRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetRepo", reflect.TypeOf((*MockPushNotice)(nil).GetTargetRepo))
}

// SetTargetRepo mocks base method
func (m *MockPushNotice) SetTargetRepo(repo types2.LocalRepo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTargetRepo", repo)
}

// SetTargetRepo indicates an expected call of SetTargetRepo
func (mr *MockPushNoticeMockRecorder) SetTargetRepo(repo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTargetRepo", reflect.TypeOf((*MockPushNotice)(nil).SetTargetRepo), repo)
}

// GetPusherKeyID mocks base method
func (m *MockPushNotice) GetPusherKeyID() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPusherKeyID")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetPusherKeyID indicates an expected call of GetPusherKeyID
func (mr *MockPushNoticeMockRecorder) GetPusherKeyID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPusherKeyID", reflect.TypeOf((*MockPushNotice)(nil).GetPusherKeyID))
}

// GetPusherAddress mocks base method
func (m *MockPushNotice) GetPusherAddress() util.Address {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPusherAddress")
	ret0, _ := ret[0].(util.Address)
	return ret0
}

// GetPusherAddress indicates an expected call of GetPusherAddress
func (mr *MockPushNoticeMockRecorder) GetPusherAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPusherAddress", reflect.TypeOf((*MockPushNotice)(nil).GetPusherAddress))
}

// GetPusherAccountNonce mocks base method
func (m *MockPushNotice) GetPusherAccountNonce() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPusherAccountNonce")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetPusherAccountNonce indicates an expected call of GetPusherAccountNonce
func (mr *MockPushNoticeMockRecorder) GetPusherAccountNonce() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPusherAccountNonce", reflect.TypeOf((*MockPushNotice)(nil).GetPusherAccountNonce))
}

// GetPusherKeyIDString mocks base method
func (m *MockPushNotice) GetPusherKeyIDString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPusherKeyIDString")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPusherKeyIDString indicates an expected call of GetPusherKeyIDString
func (mr *MockPushNoticeMockRecorder) GetPusherKeyIDString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPusherKeyIDString", reflect.TypeOf((*MockPushNotice)(nil).GetPusherKeyIDString))
}

// EncodeMsgpack mocks base method
func (m *MockPushNotice) EncodeMsgpack(enc *msgpack.Encoder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncodeMsgpack", enc)
	ret0, _ := ret[0].(error)
	return ret0
}

// EncodeMsgpack indicates an expected call of EncodeMsgpack
func (mr *MockPushNoticeMockRecorder) EncodeMsgpack(enc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncodeMsgpack", reflect.TypeOf((*MockPushNotice)(nil).EncodeMsgpack), enc)
}

// DecodeMsgpack mocks base method
func (m *MockPushNotice) DecodeMsgpack(dec *msgpack.Decoder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeMsgpack", dec)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecodeMsgpack indicates an expected call of DecodeMsgpack
func (mr *MockPushNoticeMockRecorder) DecodeMsgpack(dec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeMsgpack", reflect.TypeOf((*MockPushNotice)(nil).DecodeMsgpack), dec)
}

// Bytes mocks base method
func (m *MockPushNotice) Bytes(recompute ...bool) []byte {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range recompute {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Bytes", varargs...)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Bytes indicates an expected call of Bytes
func (mr *MockPushNoticeMockRecorder) Bytes(recompute ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bytes", reflect.TypeOf((*MockPushNotice)(nil).Bytes), recompute...)
}

// BytesNoCache mocks base method
func (m *MockPushNotice) BytesNoCache() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BytesNoCache")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// BytesNoCache indicates an expected call of BytesNoCache
func (mr *MockPushNoticeMockRecorder) BytesNoCache() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BytesNoCache", reflect.TypeOf((*MockPushNotice)(nil).BytesNoCache))
}

// BytesNoSig mocks base method
func (m *MockPushNotice) BytesNoSig() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BytesNoSig")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// BytesNoSig indicates an expected call of BytesNoSig
func (mr *MockPushNoticeMockRecorder) BytesNoSig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BytesNoSig", reflect.TypeOf((*MockPushNotice)(nil).BytesNoSig))
}

// GetPushedObjects mocks base method
func (m *MockPushNotice) GetPushedObjects() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushedObjects")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetPushedObjects indicates an expected call of GetPushedObjects
func (mr *MockPushNoticeMockRecorder) GetPushedObjects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushedObjects", reflect.TypeOf((*MockPushNotice)(nil).GetPushedObjects))
}

// GetEcoSize mocks base method
func (m *MockPushNotice) GetEcoSize() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEcoSize")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetEcoSize indicates an expected call of GetEcoSize
func (mr *MockPushNoticeMockRecorder) GetEcoSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEcoSize", reflect.TypeOf((*MockPushNotice)(nil).GetEcoSize))
}

// GetNodePubKey mocks base method
func (m *MockPushNotice) GetNodePubKey() util.Bytes32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodePubKey")
	ret0, _ := ret[0].(util.Bytes32)
	return ret0
}

// GetNodePubKey indicates an expected call of GetNodePubKey
func (mr *MockPushNoticeMockRecorder) GetNodePubKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodePubKey", reflect.TypeOf((*MockPushNotice)(nil).GetNodePubKey))
}

// GetNodeSignature mocks base method
func (m *MockPushNotice) GetNodeSignature() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeSignature")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetNodeSignature indicates an expected call of GetNodeSignature
func (mr *MockPushNoticeMockRecorder) GetNodeSignature() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeSignature", reflect.TypeOf((*MockPushNotice)(nil).GetNodeSignature))
}

// GetRepoName mocks base method
func (m *MockPushNotice) GetRepoName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepoName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRepoName indicates an expected call of GetRepoName
func (mr *MockPushNoticeMockRecorder) GetRepoName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepoName", reflect.TypeOf((*MockPushNotice)(nil).GetRepoName))
}

// GetNamespace mocks base method
func (m *MockPushNotice) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace
func (mr *MockPushNoticeMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockPushNotice)(nil).GetNamespace))
}

// GetTimestamp mocks base method
func (m *MockPushNotice) GetTimestamp() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimestamp")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetTimestamp indicates an expected call of GetTimestamp
func (mr *MockPushNoticeMockRecorder) GetTimestamp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimestamp", reflect.TypeOf((*MockPushNotice)(nil).GetTimestamp))
}

// GetPushedReferences mocks base method
func (m *MockPushNotice) GetPushedReferences() types.PushedReferences {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPushedReferences")
	ret0, _ := ret[0].(types.PushedReferences)
	return ret0
}

// GetPushedReferences indicates an expected call of GetPushedReferences
func (mr *MockPushNoticeMockRecorder) GetPushedReferences() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPushedReferences", reflect.TypeOf((*MockPushNotice)(nil).GetPushedReferences))
}

// Len mocks base method
func (m *MockPushNotice) Len() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Len indicates an expected call of Len
func (mr *MockPushNoticeMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockPushNotice)(nil).Len))
}

// ID mocks base method
func (m *MockPushNotice) ID(recompute ...bool) util.Bytes32 {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range recompute {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ID", varargs...)
	ret0, _ := ret[0].(util.Bytes32)
	return ret0
}

// ID indicates an expected call of ID
func (mr *MockPushNoticeMockRecorder) ID(recompute ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockPushNotice)(nil).ID), recompute...)
}

// BytesAndID mocks base method
func (m *MockPushNotice) BytesAndID(recompute ...bool) ([]byte, util.Bytes32) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range recompute {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BytesAndID", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(util.Bytes32)
	return ret0, ret1
}

// BytesAndID indicates an expected call of BytesAndID
func (mr *MockPushNoticeMockRecorder) BytesAndID(recompute ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BytesAndID", reflect.TypeOf((*MockPushNotice)(nil).BytesAndID), recompute...)
}

// TxSize mocks base method
func (m *MockPushNotice) TxSize() uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxSize")
	ret0, _ := ret[0].(uint)
	return ret0
}

// TxSize indicates an expected call of TxSize
func (mr *MockPushNoticeMockRecorder) TxSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxSize", reflect.TypeOf((*MockPushNotice)(nil).TxSize))
}

// BillableSize mocks base method
func (m *MockPushNotice) BillableSize() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BillableSize")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// BillableSize indicates an expected call of BillableSize
func (mr *MockPushNoticeMockRecorder) BillableSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BillableSize", reflect.TypeOf((*MockPushNotice)(nil).BillableSize))
}

// GetSize mocks base method
func (m *MockPushNotice) GetSize() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSize")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetSize indicates an expected call of GetSize
func (mr *MockPushNoticeMockRecorder) GetSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSize", reflect.TypeOf((*MockPushNotice)(nil).GetSize))
}

// GetFee mocks base method
func (m *MockPushNotice) GetFee() util.String {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFee")
	ret0, _ := ret[0].(util.String)
	return ret0
}

// GetFee indicates an expected call of GetFee
func (mr *MockPushNoticeMockRecorder) GetFee() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFee", reflect.TypeOf((*MockPushNotice)(nil).GetFee))
}

// MockLocalRepo is a mock of LocalRepo interface
type MockLocalRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLocalRepoMockRecorder
}

// MockLocalRepoMockRecorder is the mock recorder for MockLocalRepo
type MockLocalRepoMockRecorder struct {
	mock *MockLocalRepo
}

// NewMockLocalRepo creates a new mock instance
func NewMockLocalRepo(ctrl *gomock.Controller) *MockLocalRepo {
	mock := &MockLocalRepo{ctrl: ctrl}
	mock.recorder = &MockLocalRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLocalRepo) EXPECT() *MockLocalRepoMockRecorder {
	return m.recorder
}

// RefDelete mocks base method
func (m *MockLocalRepo) RefDelete(refname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefDelete", refname)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefDelete indicates an expected call of RefDelete
func (mr *MockLocalRepoMockRecorder) RefDelete(refname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefDelete", reflect.TypeOf((*MockLocalRepo)(nil).RefDelete), refname)
}

// RefUpdate mocks base method
func (m *MockLocalRepo) RefUpdate(refname, commitHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefUpdate", refname, commitHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefUpdate indicates an expected call of RefUpdate
func (mr *MockLocalRepoMockRecorder) RefUpdate(refname, commitHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefUpdate", reflect.TypeOf((*MockLocalRepo)(nil).RefUpdate), refname, commitHash)
}

// TagDelete mocks base method
func (m *MockLocalRepo) TagDelete(tagname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagDelete", tagname)
	ret0, _ := ret[0].(error)
	return ret0
}

// TagDelete indicates an expected call of TagDelete
func (mr *MockLocalRepoMockRecorder) TagDelete(tagname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagDelete", reflect.TypeOf((*MockLocalRepo)(nil).TagDelete), tagname)
}

// RefGet mocks base method
func (m *MockLocalRepo) RefGet(refname string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefGet", refname)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefGet indicates an expected call of RefGet
func (mr *MockLocalRepoMockRecorder) RefGet(refname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefGet", reflect.TypeOf((*MockLocalRepo)(nil).RefGet), refname)
}

// GetRecentCommitHash mocks base method
func (m *MockLocalRepo) GetRecentCommitHash() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentCommitHash")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentCommitHash indicates an expected call of GetRecentCommitHash
func (mr *MockLocalRepoMockRecorder) GetRecentCommitHash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentCommitHash", reflect.TypeOf((*MockLocalRepo)(nil).GetRecentCommitHash))
}

// GetHEAD mocks base method
func (m *MockLocalRepo) GetHEAD(short bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHEAD", short)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHEAD indicates an expected call of GetHEAD
func (mr *MockLocalRepoMockRecorder) GetHEAD(short interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHEAD", reflect.TypeOf((*MockLocalRepo)(nil).GetHEAD), short)
}

// NumCommits mocks base method
func (m *MockLocalRepo) NumCommits(branch string, noMerges bool) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumCommits", branch, noMerges)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NumCommits indicates an expected call of NumCommits
func (mr *MockLocalRepoMockRecorder) NumCommits(branch, noMerges interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumCommits", reflect.TypeOf((*MockLocalRepo)(nil).NumCommits), branch, noMerges)
}

// GetConfig mocks base method
func (m *MockLocalRepo) GetConfig(path string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", path)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfig indicates an expected call of GetConfig
func (mr *MockLocalRepoMockRecorder) GetConfig(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockLocalRepo)(nil).GetConfig), path)
}

// CreateSignedEmptyCommit mocks base method
func (m *MockLocalRepo) CreateSignedEmptyCommit(msg, signingKey string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{msg, signingKey}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSignedEmptyCommit", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSignedEmptyCommit indicates an expected call of CreateSignedEmptyCommit
func (mr *MockLocalRepoMockRecorder) CreateSignedEmptyCommit(msg, signingKey interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{msg, signingKey}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSignedEmptyCommit", reflect.TypeOf((*MockLocalRepo)(nil).CreateSignedEmptyCommit), varargs...)
}

// CreateTagWithMsg mocks base method
func (m *MockLocalRepo) CreateTagWithMsg(args []string, msg, signingKey string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{args, msg, signingKey}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTagWithMsg", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTagWithMsg indicates an expected call of CreateTagWithMsg
func (mr *MockLocalRepoMockRecorder) CreateTagWithMsg(args, msg, signingKey interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{args, msg, signingKey}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTagWithMsg", reflect.TypeOf((*MockLocalRepo)(nil).CreateTagWithMsg), varargs...)
}

// ListTreeObjects mocks base method
func (m *MockLocalRepo) ListTreeObjects(treename string, recursive bool, env ...string) (map[string]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{treename, recursive}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTreeObjects", varargs...)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTreeObjects indicates an expected call of ListTreeObjects
func (mr *MockLocalRepoMockRecorder) ListTreeObjects(treename, recursive interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{treename, recursive}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTreeObjects", reflect.TypeOf((*MockLocalRepo)(nil).ListTreeObjects), varargs...)
}

// ListTreeObjectsSlice mocks base method
func (m *MockLocalRepo) ListTreeObjectsSlice(treename string, recursive, showTrees bool, env ...string) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{treename, recursive, showTrees}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTreeObjectsSlice", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTreeObjectsSlice indicates an expected call of ListTreeObjectsSlice
func (mr *MockLocalRepoMockRecorder) ListTreeObjectsSlice(treename, recursive, showTrees interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{treename, recursive, showTrees}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTreeObjectsSlice", reflect.TypeOf((*MockLocalRepo)(nil).ListTreeObjectsSlice), varargs...)
}

// RemoveEntryFromNote mocks base method
func (m *MockLocalRepo) RemoveEntryFromNote(notename, objectHash string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{notename, objectHash}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveEntryFromNote", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveEntryFromNote indicates an expected call of RemoveEntryFromNote
func (mr *MockLocalRepoMockRecorder) RemoveEntryFromNote(notename, objectHash interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{notename, objectHash}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEntryFromNote", reflect.TypeOf((*MockLocalRepo)(nil).RemoveEntryFromNote), varargs...)
}

// AddEntryToNote mocks base method
func (m *MockLocalRepo) AddEntryToNote(notename, objectHash, note string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{notename, objectHash, note}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddEntryToNote", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEntryToNote indicates an expected call of AddEntryToNote
func (mr *MockLocalRepoMockRecorder) AddEntryToNote(notename, objectHash, note interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{notename, objectHash, note}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEntryToNote", reflect.TypeOf((*MockLocalRepo)(nil).AddEntryToNote), varargs...)
}

// CreateBlob mocks base method
func (m *MockLocalRepo) CreateBlob(content string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlob", content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlob indicates an expected call of CreateBlob
func (mr *MockLocalRepoMockRecorder) CreateBlob(content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlob", reflect.TypeOf((*MockLocalRepo)(nil).CreateBlob), content)
}

// UpdateRecentCommitMsg mocks base method
func (m *MockLocalRepo) UpdateRecentCommitMsg(msg, signingKey string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{msg, signingKey}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateRecentCommitMsg", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRecentCommitMsg indicates an expected call of UpdateRecentCommitMsg
func (mr *MockLocalRepoMockRecorder) UpdateRecentCommitMsg(msg, signingKey interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{msg, signingKey}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecentCommitMsg", reflect.TypeOf((*MockLocalRepo)(nil).UpdateRecentCommitMsg), varargs...)
}

// IsAncestor mocks base method
func (m *MockLocalRepo) IsAncestor(commitA, commitB string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{commitA, commitB}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IsAncestor", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAncestor indicates an expected call of IsAncestor
func (mr *MockLocalRepoMockRecorder) IsAncestor(commitA, commitB interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{commitA, commitB}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAncestor", reflect.TypeOf((*MockLocalRepo)(nil).IsAncestor), varargs...)
}

// HasMergeCommits mocks base method
func (m *MockLocalRepo) HasMergeCommits(reference string, env ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{reference}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HasMergeCommits", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasMergeCommits indicates an expected call of HasMergeCommits
func (mr *MockLocalRepoMockRecorder) HasMergeCommits(reference interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{reference}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasMergeCommits", reflect.TypeOf((*MockLocalRepo)(nil).HasMergeCommits), varargs...)
}

// GetMergeCommits mocks base method
func (m *MockLocalRepo) GetMergeCommits(reference string, env ...string) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{reference}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMergeCommits", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMergeCommits indicates an expected call of GetMergeCommits
func (mr *MockLocalRepoMockRecorder) GetMergeCommits(reference interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{reference}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMergeCommits", reflect.TypeOf((*MockLocalRepo)(nil).GetMergeCommits), varargs...)
}

// CreateSingleFileCommit mocks base method
func (m *MockLocalRepo) CreateSingleFileCommit(filename, content, commitMsg, parent string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSingleFileCommit", filename, content, commitMsg, parent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSingleFileCommit indicates an expected call of CreateSingleFileCommit
func (mr *MockLocalRepoMockRecorder) CreateSingleFileCommit(filename, content, commitMsg, parent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSingleFileCommit", reflect.TypeOf((*MockLocalRepo)(nil).CreateSingleFileCommit), filename, content, commitMsg, parent)
}

// Checkout mocks base method
func (m *MockLocalRepo) Checkout(refname string, create, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkout", refname, create, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// Checkout indicates an expected call of Checkout
func (mr *MockLocalRepoMockRecorder) Checkout(refname, create, force interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockLocalRepo)(nil).Checkout), refname, create, force)
}

// GetRefRootCommit mocks base method
func (m *MockLocalRepo) GetRefRootCommit(ref string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefRootCommit", ref)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefRootCommit indicates an expected call of GetRefRootCommit
func (mr *MockLocalRepoMockRecorder) GetRefRootCommit(ref interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefRootCommit", reflect.TypeOf((*MockLocalRepo)(nil).GetRefRootCommit), ref)
}

// GetRefCommits mocks base method
func (m *MockLocalRepo) GetRefCommits(ref string, noMerges bool) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefCommits", ref, noMerges)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefCommits indicates an expected call of GetRefCommits
func (mr *MockLocalRepoMockRecorder) GetRefCommits(ref, noMerges interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefCommits", reflect.TypeOf((*MockLocalRepo)(nil).GetRefCommits), ref, noMerges)
}

// Var mocks base method
func (m *MockLocalRepo) Var(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Var", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Var indicates an expected call of Var
func (mr *MockLocalRepoMockRecorder) Var(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Var", reflect.TypeOf((*MockLocalRepo)(nil).Var), name)
}

// ExpandShortHash mocks base method
func (m *MockLocalRepo) ExpandShortHash(hash string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpandShortHash", hash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpandShortHash indicates an expected call of ExpandShortHash
func (mr *MockLocalRepoMockRecorder) ExpandShortHash(hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpandShortHash", reflect.TypeOf((*MockLocalRepo)(nil).ExpandShortHash), hash)
}

// GetName mocks base method
func (m *MockLocalRepo) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName
func (mr *MockLocalRepoMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockLocalRepo)(nil).GetName))
}

// GetNameFromPath mocks base method
func (m *MockLocalRepo) GetNameFromPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNameFromPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNameFromPath indicates an expected call of GetNameFromPath
func (mr *MockLocalRepoMockRecorder) GetNameFromPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNameFromPath", reflect.TypeOf((*MockLocalRepo)(nil).GetNameFromPath))
}

// GetNamespaceName mocks base method
func (m *MockLocalRepo) GetNamespaceName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespaceName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespaceName indicates an expected call of GetNamespaceName
func (mr *MockLocalRepoMockRecorder) GetNamespaceName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespaceName", reflect.TypeOf((*MockLocalRepo)(nil).GetNamespaceName))
}

// GetNamespace mocks base method
func (m *MockLocalRepo) GetNamespace() *state.Namespace {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(*state.Namespace)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace
func (mr *MockLocalRepoMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockLocalRepo)(nil).GetNamespace))
}

// References mocks base method
func (m *MockLocalRepo) References() (storer.ReferenceIter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "References")
	ret0, _ := ret[0].(storer.ReferenceIter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// References indicates an expected call of References
func (mr *MockLocalRepoMockRecorder) References() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "References", reflect.TypeOf((*MockLocalRepo)(nil).References))
}

// IsContributor mocks base method
func (m *MockLocalRepo) IsContributor(pushKeyID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsContributor", pushKeyID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsContributor indicates an expected call of IsContributor
func (mr *MockLocalRepoMockRecorder) IsContributor(pushKeyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsContributor", reflect.TypeOf((*MockLocalRepo)(nil).IsContributor), pushKeyID)
}

// GetRemoteURLs mocks base method
func (m *MockLocalRepo) GetRemoteURLs() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteURLs")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetRemoteURLs indicates an expected call of GetRemoteURLs
func (mr *MockLocalRepoMockRecorder) GetRemoteURLs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteURLs", reflect.TypeOf((*MockLocalRepo)(nil).GetRemoteURLs))
}

// DeleteObject mocks base method
func (m *MockLocalRepo) DeleteObject(hash plumbing.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject
func (mr *MockLocalRepoMockRecorder) DeleteObject(hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockLocalRepo)(nil).DeleteObject), hash)
}

// Reference mocks base method
func (m *MockLocalRepo) Reference(name plumbing.ReferenceName, resolved bool) (*plumbing.Reference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reference", name, resolved)
	ret0, _ := ret[0].(*plumbing.Reference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reference indicates an expected call of Reference
func (mr *MockLocalRepoMockRecorder) Reference(name, resolved interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reference", reflect.TypeOf((*MockLocalRepo)(nil).Reference), name, resolved)
}

// Object mocks base method
func (m *MockLocalRepo) Object(t plumbing.ObjectType, h plumbing.Hash) (object.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Object", t, h)
	ret0, _ := ret[0].(object.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Object indicates an expected call of Object
func (mr *MockLocalRepoMockRecorder) Object(t, h interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Object", reflect.TypeOf((*MockLocalRepo)(nil).Object), t, h)
}

// Objects mocks base method
func (m *MockLocalRepo) Objects() (*object.ObjectIter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Objects")
	ret0, _ := ret[0].(*object.ObjectIter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Objects indicates an expected call of Objects
func (mr *MockLocalRepoMockRecorder) Objects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Objects", reflect.TypeOf((*MockLocalRepo)(nil).Objects))
}

// CommitObjects mocks base method
func (m *MockLocalRepo) CommitObjects() (object.CommitIter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitObjects")
	ret0, _ := ret[0].(object.CommitIter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitObjects indicates an expected call of CommitObjects
func (mr *MockLocalRepoMockRecorder) CommitObjects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitObjects", reflect.TypeOf((*MockLocalRepo)(nil).CommitObjects))
}

// CommitObject mocks base method
func (m *MockLocalRepo) CommitObject(h plumbing.Hash) (*object.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitObject", h)
	ret0, _ := ret[0].(*object.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitObject indicates an expected call of CommitObject
func (mr *MockLocalRepoMockRecorder) CommitObject(h interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitObject", reflect.TypeOf((*MockLocalRepo)(nil).CommitObject), h)
}

// WrappedCommitObject mocks base method
func (m *MockLocalRepo) WrappedCommitObject(h plumbing.Hash) (types2.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WrappedCommitObject", h)
	ret0, _ := ret[0].(types2.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WrappedCommitObject indicates an expected call of WrappedCommitObject
func (mr *MockLocalRepoMockRecorder) WrappedCommitObject(h interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WrappedCommitObject", reflect.TypeOf((*MockLocalRepo)(nil).WrappedCommitObject), h)
}

// BlobObject mocks base method
func (m *MockLocalRepo) BlobObject(h plumbing.Hash) (*object.Blob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlobObject", h)
	ret0, _ := ret[0].(*object.Blob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlobObject indicates an expected call of BlobObject
func (mr *MockLocalRepoMockRecorder) BlobObject(h interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlobObject", reflect.TypeOf((*MockLocalRepo)(nil).BlobObject), h)
}

// TagObject mocks base method
func (m *MockLocalRepo) TagObject(h plumbing.Hash) (*object.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagObject", h)
	ret0, _ := ret[0].(*object.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagObject indicates an expected call of TagObject
func (mr *MockLocalRepoMockRecorder) TagObject(h interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagObject", reflect.TypeOf((*MockLocalRepo)(nil).TagObject), h)
}

// Tag mocks base method
func (m *MockLocalRepo) Tag(name string) (*plumbing.Reference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tag", name)
	ret0, _ := ret[0].(*plumbing.Reference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tag indicates an expected call of Tag
func (mr *MockLocalRepoMockRecorder) Tag(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tag", reflect.TypeOf((*MockLocalRepo)(nil).Tag), name)
}

// Config mocks base method
func (m *MockLocalRepo) Config() (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Config indicates an expected call of Config
func (mr *MockLocalRepoMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockLocalRepo)(nil).Config))
}

// SetConfig mocks base method
func (m *MockLocalRepo) SetConfig(cfg *config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConfig", cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConfig indicates an expected call of SetConfig
func (mr *MockLocalRepoMockRecorder) SetConfig(cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfig", reflect.TypeOf((*MockLocalRepo)(nil).SetConfig), cfg)
}

// SetPath mocks base method
func (m *MockLocalRepo) SetPath(path string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPath", path)
}

// SetPath indicates an expected call of SetPath
func (mr *MockLocalRepoMockRecorder) SetPath(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPath", reflect.TypeOf((*MockLocalRepo)(nil).SetPath), path)
}

// GetReferences mocks base method
func (m *MockLocalRepo) GetReferences() ([]plumbing.ReferenceName, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferences")
	ret0, _ := ret[0].([]plumbing.ReferenceName)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReferences indicates an expected call of GetReferences
func (mr *MockLocalRepoMockRecorder) GetReferences() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferences", reflect.TypeOf((*MockLocalRepo)(nil).GetReferences))
}

// GetPath mocks base method
func (m *MockLocalRepo) GetPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPath indicates an expected call of GetPath
func (mr *MockLocalRepoMockRecorder) GetPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPath", reflect.TypeOf((*MockLocalRepo)(nil).GetPath))
}

// GetState mocks base method
func (m *MockLocalRepo) GetState() *state.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState")
	ret0, _ := ret[0].(*state.Repository)
	return ret0
}

// GetState indicates an expected call of GetState
func (mr *MockLocalRepoMockRecorder) GetState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockLocalRepo)(nil).GetState))
}

// SetState mocks base method
func (m *MockLocalRepo) SetState(s *state.Repository) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetState", s)
}

// SetState indicates an expected call of SetState
func (mr *MockLocalRepoMockRecorder) SetState(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetState", reflect.TypeOf((*MockLocalRepo)(nil).SetState), s)
}

// Head mocks base method
func (m *MockLocalRepo) Head() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Head")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Head indicates an expected call of Head
func (mr *MockLocalRepoMockRecorder) Head() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Head", reflect.TypeOf((*MockLocalRepo)(nil).Head))
}

// ObjectExist mocks base method
func (m *MockLocalRepo) ObjectExist(objHash string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ObjectExist", objHash)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ObjectExist indicates an expected call of ObjectExist
func (mr *MockLocalRepoMockRecorder) ObjectExist(objHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObjectExist", reflect.TypeOf((*MockLocalRepo)(nil).ObjectExist), objHash)
}

// GetObjectSize mocks base method
func (m *MockLocalRepo) GetObjectSize(objHash string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectSize", objHash)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectSize indicates an expected call of GetObjectSize
func (mr *MockLocalRepoMockRecorder) GetObjectSize(objHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectSize", reflect.TypeOf((*MockLocalRepo)(nil).GetObjectSize), objHash)
}

// GetObjectDiskSize mocks base method
func (m *MockLocalRepo) GetObjectDiskSize(objHash string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectDiskSize", objHash)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectDiskSize indicates an expected call of GetObjectDiskSize
func (mr *MockLocalRepoMockRecorder) GetObjectDiskSize(objHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectDiskSize", reflect.TypeOf((*MockLocalRepo)(nil).GetObjectDiskSize), objHash)
}

// GetEncodedObject mocks base method
func (m *MockLocalRepo) GetEncodedObject(objHash string) (plumbing.EncodedObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncodedObject", objHash)
	ret0, _ := ret[0].(plumbing.EncodedObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncodedObject indicates an expected call of GetEncodedObject
func (mr *MockLocalRepoMockRecorder) GetEncodedObject(objHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncodedObject", reflect.TypeOf((*MockLocalRepo)(nil).GetEncodedObject), objHash)
}

// WriteObjectToFile mocks base method
func (m *MockLocalRepo) WriteObjectToFile(objectHash string, content []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteObjectToFile", objectHash, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteObjectToFile indicates an expected call of WriteObjectToFile
func (mr *MockLocalRepoMockRecorder) WriteObjectToFile(objectHash, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteObjectToFile", reflect.TypeOf((*MockLocalRepo)(nil).WriteObjectToFile), objectHash, content)
}

// GetObject mocks base method
func (m *MockLocalRepo) GetObject(objHash string) (object.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", objHash)
	ret0, _ := ret[0].(object.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject
func (mr *MockLocalRepoMockRecorder) GetObject(objHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockLocalRepo)(nil).GetObject), objHash)
}

// GetCompressedObject mocks base method
func (m *MockLocalRepo) GetCompressedObject(hash string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompressedObject", hash)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompressedObject indicates an expected call of GetCompressedObject
func (mr *MockLocalRepoMockRecorder) GetCompressedObject(hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompressedObject", reflect.TypeOf((*MockLocalRepo)(nil).GetCompressedObject), hash)
}

// GetHost mocks base method
func (m *MockLocalRepo) GetHost() storage.Storer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHost")
	ret0, _ := ret[0].(storage.Storer)
	return ret0
}

// GetHost indicates an expected call of GetHost
func (mr *MockLocalRepoMockRecorder) GetHost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHost", reflect.TypeOf((*MockLocalRepo)(nil).GetHost))
}

// Prune mocks base method
func (m *MockLocalRepo) Prune(olderThan time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prune", olderThan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Prune indicates an expected call of Prune
func (mr *MockLocalRepoMockRecorder) Prune(olderThan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prune", reflect.TypeOf((*MockLocalRepo)(nil).Prune), olderThan)
}

// NumIssueBranches mocks base method
func (m *MockLocalRepo) NumIssueBranches() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumIssueBranches")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NumIssueBranches indicates an expected call of NumIssueBranches
func (mr *MockLocalRepoMockRecorder) NumIssueBranches() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumIssueBranches", reflect.TypeOf((*MockLocalRepo)(nil).NumIssueBranches))
}

// GetAncestors mocks base method
func (m *MockLocalRepo) GetAncestors(commit *object.Commit, stopHash string, reverse bool) ([]*object.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAncestors", commit, stopHash, reverse)
	ret0, _ := ret[0].([]*object.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAncestors indicates an expected call of GetAncestors
func (mr *MockLocalRepoMockRecorder) GetAncestors(commit, stopHash, reverse interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAncestors", reflect.TypeOf((*MockLocalRepo)(nil).GetAncestors), commit, stopHash, reverse)
}

// MockLiteGit is a mock of LiteGit interface
type MockLiteGit struct {
	ctrl     *gomock.Controller
	recorder *MockLiteGitMockRecorder
}

// MockLiteGitMockRecorder is the mock recorder for MockLiteGit
type MockLiteGitMockRecorder struct {
	mock *MockLiteGit
}

// NewMockLiteGit creates a new mock instance
func NewMockLiteGit(ctrl *gomock.Controller) *MockLiteGit {
	mock := &MockLiteGit{ctrl: ctrl}
	mock.recorder = &MockLiteGitMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLiteGit) EXPECT() *MockLiteGitMockRecorder {
	return m.recorder
}

// RefDelete mocks base method
func (m *MockLiteGit) RefDelete(refname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefDelete", refname)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefDelete indicates an expected call of RefDelete
func (mr *MockLiteGitMockRecorder) RefDelete(refname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefDelete", reflect.TypeOf((*MockLiteGit)(nil).RefDelete), refname)
}

// RefUpdate mocks base method
func (m *MockLiteGit) RefUpdate(refname, commitHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefUpdate", refname, commitHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefUpdate indicates an expected call of RefUpdate
func (mr *MockLiteGitMockRecorder) RefUpdate(refname, commitHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefUpdate", reflect.TypeOf((*MockLiteGit)(nil).RefUpdate), refname, commitHash)
}

// TagDelete mocks base method
func (m *MockLiteGit) TagDelete(tagname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagDelete", tagname)
	ret0, _ := ret[0].(error)
	return ret0
}

// TagDelete indicates an expected call of TagDelete
func (mr *MockLiteGitMockRecorder) TagDelete(tagname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagDelete", reflect.TypeOf((*MockLiteGit)(nil).TagDelete), tagname)
}

// RefGet mocks base method
func (m *MockLiteGit) RefGet(refname string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefGet", refname)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefGet indicates an expected call of RefGet
func (mr *MockLiteGitMockRecorder) RefGet(refname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefGet", reflect.TypeOf((*MockLiteGit)(nil).RefGet), refname)
}

// GetRecentCommitHash mocks base method
func (m *MockLiteGit) GetRecentCommitHash() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentCommitHash")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentCommitHash indicates an expected call of GetRecentCommitHash
func (mr *MockLiteGitMockRecorder) GetRecentCommitHash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentCommitHash", reflect.TypeOf((*MockLiteGit)(nil).GetRecentCommitHash))
}

// GetHEAD mocks base method
func (m *MockLiteGit) GetHEAD(short bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHEAD", short)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHEAD indicates an expected call of GetHEAD
func (mr *MockLiteGitMockRecorder) GetHEAD(short interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHEAD", reflect.TypeOf((*MockLiteGit)(nil).GetHEAD), short)
}

// NumCommits mocks base method
func (m *MockLiteGit) NumCommits(branch string, noMerges bool) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumCommits", branch, noMerges)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NumCommits indicates an expected call of NumCommits
func (mr *MockLiteGitMockRecorder) NumCommits(branch, noMerges interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumCommits", reflect.TypeOf((*MockLiteGit)(nil).NumCommits), branch, noMerges)
}

// GetConfig mocks base method
func (m *MockLiteGit) GetConfig(path string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", path)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfig indicates an expected call of GetConfig
func (mr *MockLiteGitMockRecorder) GetConfig(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockLiteGit)(nil).GetConfig), path)
}

// CreateSignedEmptyCommit mocks base method
func (m *MockLiteGit) CreateSignedEmptyCommit(msg, signingKey string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{msg, signingKey}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSignedEmptyCommit", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSignedEmptyCommit indicates an expected call of CreateSignedEmptyCommit
func (mr *MockLiteGitMockRecorder) CreateSignedEmptyCommit(msg, signingKey interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{msg, signingKey}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSignedEmptyCommit", reflect.TypeOf((*MockLiteGit)(nil).CreateSignedEmptyCommit), varargs...)
}

// CreateTagWithMsg mocks base method
func (m *MockLiteGit) CreateTagWithMsg(args []string, msg, signingKey string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{args, msg, signingKey}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTagWithMsg", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTagWithMsg indicates an expected call of CreateTagWithMsg
func (mr *MockLiteGitMockRecorder) CreateTagWithMsg(args, msg, signingKey interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{args, msg, signingKey}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTagWithMsg", reflect.TypeOf((*MockLiteGit)(nil).CreateTagWithMsg), varargs...)
}

// ListTreeObjects mocks base method
func (m *MockLiteGit) ListTreeObjects(treename string, recursive bool, env ...string) (map[string]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{treename, recursive}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTreeObjects", varargs...)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTreeObjects indicates an expected call of ListTreeObjects
func (mr *MockLiteGitMockRecorder) ListTreeObjects(treename, recursive interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{treename, recursive}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTreeObjects", reflect.TypeOf((*MockLiteGit)(nil).ListTreeObjects), varargs...)
}

// ListTreeObjectsSlice mocks base method
func (m *MockLiteGit) ListTreeObjectsSlice(treename string, recursive, showTrees bool, env ...string) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{treename, recursive, showTrees}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTreeObjectsSlice", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTreeObjectsSlice indicates an expected call of ListTreeObjectsSlice
func (mr *MockLiteGitMockRecorder) ListTreeObjectsSlice(treename, recursive, showTrees interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{treename, recursive, showTrees}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTreeObjectsSlice", reflect.TypeOf((*MockLiteGit)(nil).ListTreeObjectsSlice), varargs...)
}

// RemoveEntryFromNote mocks base method
func (m *MockLiteGit) RemoveEntryFromNote(notename, objectHash string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{notename, objectHash}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveEntryFromNote", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveEntryFromNote indicates an expected call of RemoveEntryFromNote
func (mr *MockLiteGitMockRecorder) RemoveEntryFromNote(notename, objectHash interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{notename, objectHash}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEntryFromNote", reflect.TypeOf((*MockLiteGit)(nil).RemoveEntryFromNote), varargs...)
}

// AddEntryToNote mocks base method
func (m *MockLiteGit) AddEntryToNote(notename, objectHash, note string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{notename, objectHash, note}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddEntryToNote", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEntryToNote indicates an expected call of AddEntryToNote
func (mr *MockLiteGitMockRecorder) AddEntryToNote(notename, objectHash, note interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{notename, objectHash, note}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEntryToNote", reflect.TypeOf((*MockLiteGit)(nil).AddEntryToNote), varargs...)
}

// CreateBlob mocks base method
func (m *MockLiteGit) CreateBlob(content string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlob", content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlob indicates an expected call of CreateBlob
func (mr *MockLiteGitMockRecorder) CreateBlob(content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlob", reflect.TypeOf((*MockLiteGit)(nil).CreateBlob), content)
}

// UpdateRecentCommitMsg mocks base method
func (m *MockLiteGit) UpdateRecentCommitMsg(msg, signingKey string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{msg, signingKey}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateRecentCommitMsg", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRecentCommitMsg indicates an expected call of UpdateRecentCommitMsg
func (mr *MockLiteGitMockRecorder) UpdateRecentCommitMsg(msg, signingKey interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{msg, signingKey}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecentCommitMsg", reflect.TypeOf((*MockLiteGit)(nil).UpdateRecentCommitMsg), varargs...)
}

// IsAncestor mocks base method
func (m *MockLiteGit) IsAncestor(commitA, commitB string, env ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{commitA, commitB}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IsAncestor", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAncestor indicates an expected call of IsAncestor
func (mr *MockLiteGitMockRecorder) IsAncestor(commitA, commitB interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{commitA, commitB}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAncestor", reflect.TypeOf((*MockLiteGit)(nil).IsAncestor), varargs...)
}

// HasMergeCommits mocks base method
func (m *MockLiteGit) HasMergeCommits(reference string, env ...string) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{reference}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HasMergeCommits", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasMergeCommits indicates an expected call of HasMergeCommits
func (mr *MockLiteGitMockRecorder) HasMergeCommits(reference interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{reference}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasMergeCommits", reflect.TypeOf((*MockLiteGit)(nil).HasMergeCommits), varargs...)
}

// GetMergeCommits mocks base method
func (m *MockLiteGit) GetMergeCommits(reference string, env ...string) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{reference}
	for _, a := range env {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMergeCommits", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMergeCommits indicates an expected call of GetMergeCommits
func (mr *MockLiteGitMockRecorder) GetMergeCommits(reference interface{}, env ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{reference}, env...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMergeCommits", reflect.TypeOf((*MockLiteGit)(nil).GetMergeCommits), varargs...)
}

// CreateSingleFileCommit mocks base method
func (m *MockLiteGit) CreateSingleFileCommit(filename, content, commitMsg, parent string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSingleFileCommit", filename, content, commitMsg, parent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSingleFileCommit indicates an expected call of CreateSingleFileCommit
func (mr *MockLiteGitMockRecorder) CreateSingleFileCommit(filename, content, commitMsg, parent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSingleFileCommit", reflect.TypeOf((*MockLiteGit)(nil).CreateSingleFileCommit), filename, content, commitMsg, parent)
}

// Checkout mocks base method
func (m *MockLiteGit) Checkout(refname string, create, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkout", refname, create, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// Checkout indicates an expected call of Checkout
func (mr *MockLiteGitMockRecorder) Checkout(refname, create, force interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockLiteGit)(nil).Checkout), refname, create, force)
}

// GetRefRootCommit mocks base method
func (m *MockLiteGit) GetRefRootCommit(ref string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefRootCommit", ref)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefRootCommit indicates an expected call of GetRefRootCommit
func (mr *MockLiteGitMockRecorder) GetRefRootCommit(ref interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefRootCommit", reflect.TypeOf((*MockLiteGit)(nil).GetRefRootCommit), ref)
}

// GetRefCommits mocks base method
func (m *MockLiteGit) GetRefCommits(ref string, noMerges bool) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefCommits", ref, noMerges)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefCommits indicates an expected call of GetRefCommits
func (mr *MockLiteGitMockRecorder) GetRefCommits(ref, noMerges interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefCommits", reflect.TypeOf((*MockLiteGit)(nil).GetRefCommits), ref, noMerges)
}

// Var mocks base method
func (m *MockLiteGit) Var(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Var", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Var indicates an expected call of Var
func (mr *MockLiteGitMockRecorder) Var(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Var", reflect.TypeOf((*MockLiteGit)(nil).Var), name)
}

// ExpandShortHash mocks base method
func (m *MockLiteGit) ExpandShortHash(hash string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpandShortHash", hash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpandShortHash indicates an expected call of ExpandShortHash
func (mr *MockLiteGitMockRecorder) ExpandShortHash(hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpandShortHash", reflect.TypeOf((*MockLiteGit)(nil).ExpandShortHash), hash)
}

// MockCommit is a mock of Commit interface
type MockCommit struct {
	ctrl     *gomock.Controller
	recorder *MockCommitMockRecorder
}

// MockCommitMockRecorder is the mock recorder for MockCommit
type MockCommitMockRecorder struct {
	mock *MockCommit
}

// NewMockCommit creates a new mock instance
func NewMockCommit(ctrl *gomock.Controller) *MockCommit {
	mock := &MockCommit{ctrl: ctrl}
	mock.recorder = &MockCommitMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCommit) EXPECT() *MockCommitMockRecorder {
	return m.recorder
}

// NumParents mocks base method
func (m *MockCommit) NumParents() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumParents")
	ret0, _ := ret[0].(int)
	return ret0
}

// NumParents indicates an expected call of NumParents
func (mr *MockCommitMockRecorder) NumParents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumParents", reflect.TypeOf((*MockCommit)(nil).NumParents))
}

// Parent mocks base method
func (m *MockCommit) Parent(i int) (types2.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parent", i)
	ret0, _ := ret[0].(types2.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parent indicates an expected call of Parent
func (mr *MockCommitMockRecorder) Parent(i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parent", reflect.TypeOf((*MockCommit)(nil).Parent), i)
}

// IsParent mocks base method
func (m *MockCommit) IsParent(hash string) (bool, types2.Commit) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsParent", hash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(types2.Commit)
	return ret0, ret1
}

// IsParent indicates an expected call of IsParent
func (mr *MockCommitMockRecorder) IsParent(hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsParent", reflect.TypeOf((*MockCommit)(nil).IsParent), hash)
}

// UnWrap mocks base method
func (m *MockCommit) UnWrap() *object.Commit {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnWrap")
	ret0, _ := ret[0].(*object.Commit)
	return ret0
}

// UnWrap indicates an expected call of UnWrap
func (mr *MockCommitMockRecorder) UnWrap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnWrap", reflect.TypeOf((*MockCommit)(nil).UnWrap))
}

// GetCommitter mocks base method
func (m *MockCommit) GetCommitter() *object.Signature {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitter")
	ret0, _ := ret[0].(*object.Signature)
	return ret0
}

// GetCommitter indicates an expected call of GetCommitter
func (mr *MockCommitMockRecorder) GetCommitter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitter", reflect.TypeOf((*MockCommit)(nil).GetCommitter))
}

// GetAuthor mocks base method
func (m *MockCommit) GetAuthor() *object.Signature {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthor")
	ret0, _ := ret[0].(*object.Signature)
	return ret0
}

// GetAuthor indicates an expected call of GetAuthor
func (mr *MockCommitMockRecorder) GetAuthor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthor", reflect.TypeOf((*MockCommit)(nil).GetAuthor))
}

// GetTreeHash mocks base method
func (m *MockCommit) GetTreeHash() plumbing.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTreeHash")
	ret0, _ := ret[0].(plumbing.Hash)
	return ret0
}

// GetTreeHash indicates an expected call of GetTreeHash
func (mr *MockCommitMockRecorder) GetTreeHash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTreeHash", reflect.TypeOf((*MockCommit)(nil).GetTreeHash))
}

// GetHash mocks base method
func (m *MockCommit) GetHash() plumbing.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHash")
	ret0, _ := ret[0].(plumbing.Hash)
	return ret0
}

// GetHash indicates an expected call of GetHash
func (mr *MockCommitMockRecorder) GetHash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHash", reflect.TypeOf((*MockCommit)(nil).GetHash))
}

// GetTree mocks base method
func (m *MockCommit) GetTree() (*object.Tree, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTree")
	ret0, _ := ret[0].(*object.Tree)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTree indicates an expected call of GetTree
func (mr *MockCommitMockRecorder) GetTree() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTree", reflect.TypeOf((*MockCommit)(nil).GetTree))
}

// File mocks base method
func (m *MockCommit) File(path string) (*object.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "File", path)
	ret0, _ := ret[0].(*object.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// File indicates an expected call of File
func (mr *MockCommitMockRecorder) File(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "File", reflect.TypeOf((*MockCommit)(nil).File), path)
}
